/*
 * Dinner place cards -> Illustrator.
 * Every card for every artist on its own artboard at 1:1 (mm), sorted into layers by function:
 *   Guides (non-printing) / Cut / Crease / Perforation / Text / Artwork / Board (non-printing).
 * Die lines are spot colours (Cut, Crease, Perforation), artwork and type are Dinner Black,
 * type is live Wix Madefor Text. Board shows the lemon card for preview only.
 *
 * Install Wix Madefor Text (all weights) first. File > Scripts > Other Script...
 * Generated by placecard/illustrator/svg2ai.py - edit the source SVGs and regenerate.
 */
#target illustrator

(function () {
  try {
    var D = __DATA__;
    var MM = 72 / 25.4;
    var GAP = 20 * MM, ROWGAP = 30 * MM, MAXCOL = 4800 * MM;
    var problems = [], missingFonts = [], where = "";
    function note(what, e) {
        problems.push(where + (what ? " / " + what : "") + ": " + (e && e.message ? e.message : e) +
                      (e && e.line ? " (line " + e.line + ")" : ""));
    }

    // ---- layout: one row per design (artists across), rows stacked, wrapping into columns ----
    var rows = [], rowOf = {}, i, c;
    for (i = 0; i < D.cards.length; i++) {
        c = D.cards[i];
        var key = c.group + " / " + c.design;
        if (rowOf[key] === undefined) { rowOf[key] = rows.length; rows.push({key: key, cards: []}); }
        rows[rowOf[key]].cards.push(c);
    }
    var x0 = 0, y0 = 0, colW = 0, place = [], totalW = 0, totalH = 0;
    for (i = 0; i < rows.length; i++) {
        var rw = 0, rh = 0, k;
        for (k = 0; k < rows[i].cards.length; k++) {
            rw += rows[i].cards[k].w * MM + (k ? GAP : 0);
            rh = Math.max(rh, rows[i].cards[k].h * MM);
        }
        if (y0 > 0 && y0 + rh > MAXCOL) { x0 += colW + 4 * GAP; y0 = 0; colW = 0; }
        var xx = x0;
        for (k = 0; k < rows[i].cards.length; k++) {
            place.push({card: rows[i].cards[k], ox: xx, oy: y0});
            xx += rows[i].cards[k].w * MM + GAP;
        }
        colW = Math.max(colW, rw);
        totalW = Math.max(totalW, x0 + rw);
        y0 += rh + ROWGAP;
        totalH = Math.max(totalH, y0);
    }

    var doc = app.documents.add(DocumentColorSpace.CMYK, Math.max(totalW, 100), Math.max(totalH, 100));
    doc.rulerOrigin = [0, doc.height];

    // ---- colours ----------------------------------------------------------------------------
    function cmyk(c_, m_, y_, k_) { var x = new CMYKColor(); x.cyan = c_; x.magenta = m_; x.yellow = y_; x.black = k_; return x; }
    function spot(name, col, type) {
        try {
            var s = doc.spots.add();
            s.color = col;
            s.colorType = type;
            s.name = name;
            var sc = new SpotColor(); sc.spot = s; sc.tint = 100;
            return sc;
        } catch (e) { note("swatch " + name, e); return col; }
    }
    var BLACK = spot("Dinner Black", cmyk(0, 0, 0, 100), ColorModel.PROCESS);
    var LEMON = spot("Dinner Lemon", cmyk(0, 5, 50, 0), ColorModel.PROCESS);
    var CUT = spot("Cut", cmyk(0, 100, 0, 0), ColorModel.SPOT);
    var CREASE = spot("Crease", cmyk(100, 0, 0, 0), ColorModel.SPOT);
    var PERF = spot("Perforation", cmyk(0, 60, 100, 0), ColorModel.SPOT);
    var GUIDE = cmyk(0, 0, 0, 45);

    // ---- layers (added bottom first; each add goes on top) -------------------------------------
    var defaultLayer = doc.layers[0];
    function layer(name, printable) {
        var l = doc.layers.add();
        l.name = name;
        if (!printable) { try { l.printable = false; } catch (e) {} }
        return l;
    }
    var L = {};
    L.board = layer("Board (preview)", false);
    L.art = layer("Artwork", true);
    L.text = layer("Text", true);
    L.perf = layer("Perforation", true);
    L.crease = layer("Crease", true);
    L.cut = layer("Cut", true);
    L.guides = layer("Guides", false);
    try { if (defaultLayer.pageItems.length === 0) defaultLayer.remove(); } catch (e0) {}

    // ---- fonts ------------------------------------------------------------------------------
    var STYLE = {400: "Regular", 500: "Medium", 600: "SemiBold", 700: "Bold", 800: "ExtraBold"};
    var fontCache = {};
    function squash(s) { return String(s).toLowerCase().replace(/[^a-z]/g, ""); }
    function font(weight) {
        var w = Math.round(weight / 100) * 100;
        if (w < 400) w = 400;
        if (w > 800) w = 800;
        if (fontCache[w] !== undefined) return fontCache[w];
        var ps = "WixMadeforText-" + STYLE[w], f = null;
        try { f = app.textFonts.getByName(ps); } catch (e) { f = null; }
        if (!f) {
            var want = squash(STYLE[w]);
            for (var j = 0; j < app.textFonts.length && !f; j++) {
                try {
                    var tf = app.textFonts[j];
                    if (squash(tf.family).indexOf("wixmadefortext") === 0 && squash(tf.style) === want) f = tf;
                } catch (e2) {}
            }
        }
        if (!f) missingFonts.push(ps);
        fontCache[w] = f;
        return f;
    }

    // ---- drawing ----------------------------------------------------------------------------
    var ox, oy;
    function P(x, y) { return [ox + x * MM, -(oy + y * MM)]; }

    function buildPath(container, sp) {
        var p = container.pathItems.add();
        var anchors = [], j;
        for (j = 0; j < sp.pts.length; j++) anchors.push(P(sp.pts[j][0], sp.pts[j][1]));
        p.setEntirePath(anchors);
        for (j = 0; j < sp.pts.length; j++) {
            var q = sp.pts[j], pp = p.pathPoints[j];
            pp.leftDirection = P(q[2], q[3]);
            pp.rightDirection = P(q[4], q[5]);
        }
        p.closed = !!sp.closed;
        return p;
    }

    function style(p, it, fillCol, strokeCol) {
        if (fillCol) { p.filled = true; p.fillColor = fillCol; } else p.filled = false;
        if (strokeCol) {
            p.stroked = true;
            p.strokeColor = strokeCol;
            p.strokeWidth = Math.max(0.25, (it.sw || 0.25) * MM);
            if (it.dash && it.dash.length) {
                var d = [];
                for (var j = 0; j < it.dash.length; j++) d.push(it.dash[j] * MM);
                p.strokeDashes = d;
            }
            try { p.strokeOverprint = true; } catch (e) {}
        } else p.stroked = false;
    }

    // artwork is Dinner Black; a light fill is a lemon flood (e.g. printed on the back of the mirror ring board)
    function ink(hex) {
        var v = parseInt(String(hex).replace("#", ""), 16);
        if (isNaN(v)) return BLACK;
        var lum = 0.299 * ((v >> 16) & 255) + 0.587 * ((v >> 8) & 255) + 0.114 * (v & 255);
        return lum > 128 ? LEMON : BLACK;
    }

    function drawPath(container, it, kind) {
        var fillCol = null, strokeCol = null;
        if (kind === "cut") strokeCol = CUT;
        else if (kind === "crease") strokeCol = CREASE;
        else if (kind === "perf") strokeCol = PERF;
        else if (kind === "guides") { strokeCol = it.stroke ? GUIDE : null; fillCol = it.fill ? GUIDE : null; }
        else {
            fillCol = it.fill ? ink(it.fill) : null;
            strokeCol = it.stroke ? ink(it.stroke) : null;
        }
        if (kind === "art" && it.fill && it.sub.length > 1) {
            var cp = container.compoundPathItems.add();
            for (var j = 0; j < it.sub.length; j++) {
                var p = buildPath(cp, it.sub[j]);
                style(p, it, fillCol, strokeCol);
                try { p.evenodd = true; } catch (e) {}
            }
            return;
        }
        for (var k = 0; k < it.sub.length; k++) {
            var q = buildPath(container, it.sub[k]);
            style(q, it, fillCol, strokeCol);
        }
    }

    function drawText(container, it, kind) {
        var at = P(it.x, it.y);
        var tf = container.textFrames.pointText(at);
        tf.contents = it.s;
        var ca = tf.textRange.characterAttributes;
        var f = font(it.weight || 600);
        if (f) ca.textFont = f;
        ca.size = it.size * MM;
        try { ca.tracking = Math.round((it.ls || 0) / it.size * 1000); } catch (e1) {}
        try { ca.kerningMethod = AutoKernType.AUTO; } catch (e2) {}
        ca.fillColor = kind === "guides" ? GUIDE : BLACK;
        var j = Justification.LEFT;
        if (it.anchor === "middle") j = Justification.CENTER;
        if (it.anchor === "end") j = Justification.RIGHT;
        tf.textRange.paragraphAttributes.justification = j;
        if (it.rot) {
            tf.rotate(-it.rot);                         // SVG angles run clockwise, Illustrator's anticlockwise
            var a = tf.anchor;                          // put the baseline start back where SVG had it
            tf.translate(at[0] - a[0], at[1] - a[1]);
        }
    }

    function makeGrp(groups, label) {
        return function (kind) {
            if (!groups[kind]) { groups[kind] = L[kind].groupItems.add(); groups[kind].name = label; }
            return groups[kind];
        };
    }

    // ---- cards ------------------------------------------------------------------------------
    var made = 0;
    for (i = 0; i < place.length; i++) {
        c = place[i].card;
        ox = place[i].ox; oy = place[i].oy;
        var label = c.design + (c.artist ? " / " + c.artist : "");
        where = label;
        try {
            var rect = [ox, -oy, ox + c.w * MM, -(oy + c.h * MM)];
            var ab = made === 0 ? doc.artboards[0] : doc.artboards.add(rect);
            ab.artboardRect = rect;
            ab.name = label;
            made++;

            var groups = {};
            var grp = makeGrp(groups, label);

            // preview board: lemon under closed cut outlines, else the whole sheet
            // one compound path, even-odd, so holes and windows in the die stay open
            var b = grp("board"), closed = 0, cutItems = c.layers.cut || [], n, s, bcp = null;
            for (n = 0; n < cutItems.length; n++) {
                if (cutItems[n].t !== "path") continue;
                for (s = 0; s < cutItems[n].sub.length; s++) {
                    if (cutItems[n].sub[s].closed) {
                        if (!bcp) { bcp = b.compoundPathItems.add(); bcp.name = "lemon board"; }
                        var bp = buildPath(bcp, cutItems[n].sub[s]);
                        bp.filled = true; bp.fillColor = LEMON; bp.stroked = false;
                        try { bp.evenodd = true; } catch (eb) {}
                        closed++;
                    }
                }
            }
            if (!closed) {
                var r0 = b.pathItems.rectangle(-oy, ox, c.w * MM, c.h * MM);
                r0.filled = true; r0.fillColor = LEMON; r0.stroked = false;
            }

            var kinds = ["art", "text", "perf", "crease", "cut", "guides"];
            for (var kk = 0; kk < kinds.length; kk++) {
                var kind = kinds[kk], items = c.layers[kind];
                if (!items) continue;
                for (n = 0; n < items.length; n++) {
                    try {
                        if (items[n].t === "text") drawText(grp(kind), items[n], kind);
                        else drawPath(grp(kind), items[n], kind);
                    } catch (e3) { note(kind, e3); }
                }
            }
        } catch (e4) { note("card", e4); }
    }

    try { app.executeMenuCommand("fitall"); } catch (e5) {}
    var msg = "";
    if (missingFonts.length) msg += "Install Wix Madefor Text, then run again. Missing:\n" + missingFonts.join("\n") + "\n\n";
    if (problems.length) msg += "Built with " + problems.length + " problem(s); the rest is in place.\nPlease send this list back:\n\n" + problems.slice(0, 25).join("\n");
    if (msg) alert(msg);
  } catch (fatal) {
    alert("Place cards script stopped: " + fatal.message + (fatal.line ? " (line " + fatal.line + ")" : "") + "\nPlease send this message back.");
  }
})();
